<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.0 (Jython 2.7.0 on java1.8.0_20)" generated="20161215 16:25:17.203">
<suite source="C:\Projects\SBMSolution" name="SBMSolution" id="s1">
<suite source="C:\Projects\SBMSolution\tests" name="Tests" id="s1-s1">
<suite source="C:\Projects\SBMSolution\tests\WebTest.robot" name="WebTest" id="s1-s1-s1">
<test name="Login Test" id="s1-s1-s1-t1">
<kw library="Selenium2Library" name="Open Browser">
<doc>Opens a new browser instance to given URL.</doc>
<arguments>
<arg>${LOGIN_PAGE_URL}</arg>
<arg>${BROWSER}</arg>
</arguments>
<msg level="INFO" timestamp="20161215 16:25:27.422">Opening browser 'Chrome' to base url 'http://s1.web.sumdu.edu.ua:8080/login.jsp'</msg>
<msg level="INFO" timestamp="20161215 16:25:46.479">Got this failure java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:51347 during connect (&lt;_realsocket at 0x1d type=client open_count=1 channel=[id: 0x66a8f996, 0.0.0.0/0.0.0.0:51349] timeout=1.0&gt;)</msg>
<status endtime="20161215 16:25:46.548" starttime="20161215 16:25:27.405" status="PASS"></status>
</kw>
<kw library="ua.edu.sumdu.ta.yaroslavkuts.lab.LoginTestDataReader" name="Use Workbook">
<arguments>
<arg>C:\Projects\SBMSolution\resources\test_data\data.xlsx</arg>
</arguments>
<msg level="FAIL" timestamp="20161215 16:25:46.942">InvalidOperationException: Can't open the specified file input stream from file: 'C:ProjectsSBMSolution
esources	est_datadata.xlsx'</msg>
<status endtime="20161215 16:25:46.957" starttime="20161215 16:25:46.648" status="FAIL"></status>
</kw>
<kw type="teardown" library="Selenium2Library" name="Close Browser">
<doc>Closes the current browser.</doc>
<msg level="INFO" timestamp="20161215 16:25:49.586">Got this failure java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:51347 during connect (&lt;_realsocket at 0x3c type=client open_count=1 channel=[id: 0x9facc3f3, 0.0.0.0/0.0.0.0:51380] timeout=1.0&gt;)</msg>
<status endtime="20161215 16:25:49.662" starttime="20161215 16:25:47.006" status="PASS"></status>
</kw>
<status critical="yes" endtime="20161215 16:25:49.797" starttime="20161215 16:25:27.349" status="FAIL">InvalidOperationException: Can't open the specified file input stream from file: 'C:ProjectsSBMSolution
esources	est_datadata.xlsx'</status>
</test>
<status endtime="20161215 16:25:49.902" starttime="20161215 16:25:18.809" status="FAIL"></status>
</suite>
<status endtime="20161215 16:25:50.115" starttime="20161215 16:25:18.714" status="FAIL"></status>
</suite>
<status endtime="20161215 16:25:50.233" starttime="20161215 16:25:17.877" status="FAIL"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" name="SBMSolution" id="s1">SBMSolution</stat>
<stat pass="0" fail="1" name="Tests" id="s1-s1">SBMSolution.Tests</stat>
<stat pass="0" fail="1" name="WebTest" id="s1-s1-s1">SBMSolution.Tests.WebTest</stat>
</suite>
</statistics>
<errors>
<msg level="ERROR" timestamp="20161215 16:25:26.968">Error in file 'C:\Projects\SBMSolution\tests\WebTest.robot': Importing test library 'ua.com.test.Test' failed: ImportError: No module named com
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\jython2.7.0\Lib
  __classpath__
  __pyclasspath__/
  C:\jython2.7.0\Lib\site-packages
CLASSPATH:
  C:\jython2.7.0\jython.jar
  C:\Projects\SBMSolution\resources\lib\Helper-1.0.jar</msg>
</errors>
</robot>
